name: GameCI Workflow

on:
  push:
    branches:
      - Test_branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Unity
        uses: game-ci/setup-unity@v1
        with:
          unity-version: 2021.3.26f1

      - name: Build Unity Project
        run: |
          unity -quit -batchmode -projectPath ./MyUnityProject -executeMethod BuildScript.PerformBuild

      - name: Run Tests
        run: |
          unity -runTests -projectPath ./MyUnityProject -testPlatform editmode

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build-Artifact
          path: ./project/Builds/

          

