name: GameCI Workflow

on:
  push:
    branches:
      - main 
      - Test_branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Unity Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/unity
          key: unity-dependencies-${{ hashFiles('project/Packages/manifest.json') }}

      - name: change Dir
        id: change-dir
        run: |
          echo "Current working directory:"
          pwd
          
      - name: print Dir
        id: print-dir
        run: ls    

      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.2.0
        with:
          unity-version: 2021.3.26f1
          project-path: ./project

      - name: Build Unity Project
        run: |
          unity -quit -batchmode -projectPath ./project -executeMethod BuildScript.PerformBuild

      - name: Run Tests
        run: |
          unity -runTests -projectPath ./project -testPlatform editmode

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build-Artifact
          path: ./project/Builds/

